#+TITLE: SqL's blog
#+AUTHOR: SqL
#+OPTIONS: toc:nil num:nil
#+STARTUP: nofold
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="img/favicon.png" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/main.css" />

I use this blog to post information in a more centralized way, rather than
writing articles across my different projects.

* Current sections
:PROPERTIES:
:CUSTOM_ID: current-sections
:END:

The articles in this blog are spread across the following categories.

- [[file:programming/index.org][Programming]]
- [[file:reversing/index.org][Reverse engineering]]
- [[file:politics/index.org][Politics]]
- [[file:software/index.org][Software]]
- [[file:opinion/index.org][Opinion]]
- [[file:reference/index.org][Reference]]

* External articles
:PROPERTIES:
:CUSTOM_ID: external-articles-and-documentations
:END:

Coming soon!

* Other links and contact
:PROPERTIES:
:CUSTOM_ID: external-links
:END:

These are some external links you might find interesting:

- [[https://github.com/sqlait][GitHub]]
- [[https://tryhackme.com/p/SqL][TryHackMe profile]]

* Extra notes
:PROPERTIES:
:CUSTOM_ID: extra-notes
:END:

Here are some notes that might help when reading or navigating this blog.

- Most pages are static HTML files generated by [[https://www.gnu.org/software/emacs/][Emacs]]' [[https://orgmode.org/][Org mode]], and they can be
  displayed in console browsers such as [[https://lynx.invisible-island.net/][Lynx]] or [[https://www.gnu.org/software/emacs/manual/html_mono/eww.html][EWW]].
- There are two types of links: to an external page or site, with a solid
  underline; or to an element of the current page, with a dashed underline.

* Contributing
:PROPERTIES:
:CUSTOM_ID: contributing
:END:

Feel free to [[https://github.com/sqlait/sqlait.github.io][contribute]] to this blog if you find any errors, spelling mistakes or if you have any suggestions.

* License and credits
:PROPERTIES:
:CUSTOM_ID: license-and-credits
:END:

Copyright © 2025 SqLait. All Rights Reserved. The source code and content of this
website is covered by [[https://opensource.org/license/bsd-3-clause][BSD 3-Clause License]].
