#+TITLE: Politics Isn’t Policy Anymore — It’s a Team Sport
#+OPTIONS: toc:nil nul:nil
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="img/favicon.png" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../css/main.css" />
#+HTML_LINK_UP: index.html
#+HTML_LINK_HOME: ../index.html

In our current time and especially since the rise of social media, a shift in political discourse has occurred.

The art of changing thoughts and ideas into plans and policy seems to be changing into a game of capture the flag, where the wins and gains of the parties that compete are praised and celebrated by the followers without critical analysis of their plays.

Political interaction starts to resemble team sport more than democratic discourse. Emotions run high, loyalty trumps logic, and winning is everything. People from different teams are attacked over their believes, rather than being treated like people they're treated like the enemies from within. Unconditional love for your team and supporting their every move, this form of tribalism has taken a nasty presence in the world of politics, and not without it's consequences.

As I try to understand the root cause of this shift, several factors come into play. However one factor stand out: social media.
These platforms, used by millions fuel the existing divide amongst the population by injecting hatred, misinformation and distrust into our personalized feeds all in the name of ad revenue.
And even though not everyone will notice, these platforms are warping the way we think and interact with high level ideas and politics. Changing complex debates into simple battles without leaving much room for nuance or thought.

Social media's influence on the public discourse is far from one-dimensional. And as said previously this is and never will be a one sided issue, there are multiple factors which all contribute in varying degrees to the overall problem. Therefore splitting the topics into smaller pieces will help viewing the problem from multiple angles, which also makes it easier to retrieve certain chapters if you wish to reread the material.

* The overall decline in politics
** Algorithms push sensationalist speaking

The algorithms of social media are created to thrive on content that is sensationalistic in nature. The constant battles and drama is just something we tend to watch, which is also the reason why shows like =Real housewives of x= get many views. Viewing this type of content isn't inherently wrong, by all means enjoy it if you do. However sensationalist dialogue and presenting should be kept out of politics.

One video I often use to get this point across is an interview of Polish politician Dominik Tarczyński by Cathy Newman. The main question was why Poland (as a nation) hasn't taken any non-western refugees during the European migrant crisis. I don't want you to necessarily focus on the content of the interview, but rather how it's edited, you can watch the video [[https://www.youtube.com/watch?v=lSN7IeHBIsA][here]].

Notice the opening of the video: 'This Polish politician completely DESTROYS this woke interviewer', this line plays very well into this 'us vs. them' narrative that is very much present in the current political climate. 'us vs. them' is a common political tactic used to badmouth other political movements trying to rally the uninformed against them.

** The echo chamber effect

Because algorithms optimize to what you want to see, they might also create you a feed that is focussed on a certain political movement.
